base_url = "https://nic.dockerz.net"
compile_sass = true
title = "Nic Docker"
description = "Building skills so I can build things. Design, dev, board games, video games, other stuff too. Welcome to my little corner of the internet, it's nice to have you here."
generate_feeds = true

[markdown]

[markdown.highlighting]
highlight_code = true
theme = "solarized-light"
